import { logosLanguages, logosFrameworks, logosDatabase, logosTools } from './logo'

export const projects = [
    {
        name: 'Task Manager',
        image: '/assets/taskManager2.jpg',
        descriptionEn: 'This Ionic 6 Angular Android app empowers you to manage tasks offline. Create, edit, mark tasks complete, and delete them. View pending and completed tasks in separate lists, and track deadlines with a calendar view',
        descriptionEs: 'Esta aplicación Android Ionic 6 Angular te permite administrar tareas sin conexión. Crea, edita, marca tareas como completadas y elimínalas. Visualiza las tareas pendientes y completadas en listas separadas, y realiza un seguimiento de las fechas límite con una vista de calendario',
        technologies: [logosLanguages[2], logosLanguages[3], logosLanguages[1], logosFrameworks[1], logosTools[0], logosDatabase[1]],
        ghLink: 'https://github.com/EduGese/Task-Manager',
        demoLink: 'https://github.com/user-attachments/assets/2b04ef06-d5c1-4606-a3b3-526bda4ed2be',
        websiteLink: null,
        gif: '/assets/gifs/taskManager2.gif',
        gifOrientation: 'portrait',
    },
    {
        name: 'ScreenPulse - FrontApp',
        image: '/assets/projects/screenPulseFrontApp3.png',
        descriptionEn: 'ScreenPulse is an Angular frontend that lets you search and save movies, TV shows, and games using the OMDB API. It’s part of a full-stack app with a Node.js/Express backend and MongoDB database',
        descriptionEs: 'ScreenPulse es un frontend Angular que te permite buscar y guardar películas, series y juegos utilizando la API OMDB. Es parte de una aplicación full-stack con un backend Node.js/Express y una base de datos MongoDB',
        technologies: [logosLanguages[2], logosLanguages[3], logosFrameworks[0], logosLanguages[1], logosFrameworks[5]],
        ghLink: 'https://github.com/EduGese/ScreenPulse-frontApp',
        demoLink: 'https://youtu.be/e1ZbcnbUI2E',
        websiteLink: 'https://sreenpulse.web.app/',
        gif: '/assets/gifs/screenPulse.gif',
        gifOrientation: 'landscape',
    },
    {
        name: 'ScreenPulse-backend-Api',
        image: '/assets/projects/screenPulseFrontApp3.png',
        descriptionEn: 'Backend application built with Node.js and Express using TypeScript for strong and robust typing. It serves as the REST API integrated into the ScreenPulse-frontApp application',
        descriptionEs: 'Aplicación backend construida con Node.js y Express utilizando TypeScript para un tipado fuerte y robusto. Sirve como API REST integrada en la aplicación ScreenPulse-frontApp',
        technologies: [logosFrameworks[2], logosLanguages[1], logosDatabase[2]],
        ghLink: 'https://github.com/EduGese/ScreenPulse-backend-Api',
        demoLink: 'https://youtu.be/e1ZbcnbUI2E',
        websiteLink: null,
        gif: '/assets/gifs/screenPulse.gif',
        gifOrientation: 'landscape',
    },
    {
        name: 'The-Weather-App',
        image: '/assets/projects/theWeatherApp.png',
        descriptionEn: "The Weather App is a responsive web application (Single Page Application) developed with Angular 16.1.5 that provides real-time weather information based on the user's location upon opening the page",
        descriptionEs: "La aplicación del tiempo es una aplicación web responsive (Single Page Application) desarrollada con Angular 16.1.5 que proporciona información meteorológica en tiempo real basada en la ubicación del usuario al abrir la página",
        technologies: [logosLanguages[2], logosLanguages[3], logosFrameworks[0], logosLanguages[1]],
        ghLink: 'https://github.com/EduGese/The-Weather-App',
        demoLink: 'https://github.com/user-attachments/assets/1a07efd3-a8c5-4741-8e36-13943954d3fe',
        websiteLink: 'https://weatherapp-beff9.web.app/',
        gif: '/assets/gifs/weatherApp.gif',
        gifOrientation: 'landscape',
    },
    {
        name: 'TourNow',
        image: '/assets/projects/tourNow.png',
        descriptionEn: 'TourNow is a digital platform connecting tourism businesses with travelers. Businesses can create detailed profiles of their tours, and users can easily explore and book activities in cities like Madrid, Barcelona, and Seville',
        descriptionEs: 'TourNow es una plataforma digital que conecta a empresas turísticas con viajeros. Las empresas pueden crear perfiles detallados de sus tours y los usuarios pueden explorar y reservar fácilmente actividades en ciudades como Madrid, Barcelona y Sevilla',
        technologies: [logosLanguages[0], logosLanguages[3], logosLanguages[5], logosFrameworks[6], logosDatabase[0]],
        ghLink: 'https://github.com/EduGese/TourNow?tab=readme-ov-file',
        demoLink: 'https://youtu.be/D3eg3gU_CTs',
        websiteLink: null,
        gif: '/assets/gifs/TourNow.gif',
        gifOrientation: 'landscape',
    },
    {
        name: 'Esquivaman',
        image: '/assets/projects/esquivaman.png',
        descriptionEn: 'EsquivaMan is a fast-paced mobile game where you dodge a relentless barrage of washing machines. Test your reflexes and see how high you can score! Developed with Android Studio and Java',
        descriptionEs: 'EsquivaMan es un juego móvil frenético donde deberás esquivar una lluvia de lavadoras para sobrevivir. ¡Pon a prueba tus reflejos y alcanza la puntuación más alta! Desarrollado con Android Studio y Java',
        technologies: [logosLanguages[4], logosTools[1]],
        ghLink: 'https://github.com/EduGese/EsquivamanAndroidStudiovideogame?tab=readme-ov-file',
        demoLink: 'https://github.com/user-attachments/assets/d390a75f-14a0-47aa-a658-70a5b6e2e0db',
        websiteLink: null,
        gif: '/assets/gifs/esquivaman.gif',
        gifOrientation: 'landscape',
    },
    {
        name: 'EGS-Photography',
        image: '/assets/projects/EGS-Photography.png',
        descriptionEn: 'A conceptual mockup of a photography website, designed to showcase the visual style and user interactions. While interactive elements such as a search bar and shopping cart are included, they do not have any backend functionality ',
        descriptionEs:'Maqueta conceptual de un sitio web de fotografía, diseñado para mostrar el estilo visual y las interacciones del usuario. Si bien se incluyen elementos interactivos como una barra de búsqueda y un carrito de compras, estos no tienen ninguna funcionalidad de backend',
        technologies: [logosLanguages[2], logosLanguages[3], logosFrameworks[5]],
        ghLink: 'https://github.com/EduGese/EGS-Photography',
        demoLink: 'https://edugese.github.io/EGS-Photography/',
        websiteLink: 'https://edugese.github.io/EGS-Photography/',
        gif: '/assets/gifs/EGS-Photography.gif',
        gifOrientation: 'landscape',
    }
]
