import { logosLanguages, logosFrameworks, logosDatabase, logosTools } from './logo'

export const projects = [
    {
        name:'Task Manager',
        image: 'src/assets/projects/taskManager.png',
        description: 'This Ionic 6 Angular Android app empowers you to manage tasks offline. Create, edit, mark tasks complete, and delete them. View pending and completed tasks in separate lists, and track deadlines with a calendar view',
        technologies: [logosLanguages[2],logosLanguages[3], logosLanguages[1], logosFrameworks[1],  logosTools[0], logosDatabase[1]],
        ghLink: 'https://github.com/EduGese/Task-Manager',
        demoLink: 'https://github.com/user-attachments/assets/2b04ef06-d5c1-4606-a3b3-526bda4ed2be',
        websiteLink: null,
        gif:'src/assets/gifs/taskManager.gif',
        gifOrientation:'portrait',
    },
    {
        name:'ScreenPulse - FrontApp',
        image: 'src/assets/projects/screenPulseFrontApp3.png',
        description: 'ScreenPulse is an Angular frontend that lets you search and save movies, TV shows, and games using the OMDB API. It’s part of a full-stack app with a Node.js/Express backend and MongoDB database',
        technologies: [logosLanguages[2],logosLanguages[3],logosFrameworks[0], logosLanguages[1], logosFrameworks[5]],
        ghLink:'https://github.com/EduGese/ScreenPulse-frontApp',
        demoLink: 'https://youtu.be/e1ZbcnbUI2E',
        websiteLink: 'https://sreenpulse.web.app/',
        gif:'src/assets/gifs/screenPulse.gif',
        gifOrientation:'landscape',
    },
    {
        name:'ScreenPulse-backend-Api',
        image: 'src/assets/projects/screenPulseFrontApp3.png',
        description: 'Backend application built with Node.js and Express using TypeScript for strong and robust typing. It serves as the REST API integrated into the ScreenPulse-frontApp application',
        technologies: [logosFrameworks[2], logosLanguages[1], logosDatabase[2]],
        ghLink:'https://github.com/EduGese/ScreenPulse-backend-Api',
        demoLink: 'https://youtu.be/e1ZbcnbUI2E',
        websiteLink: null,
        gif:null,
        gifOrientation:'landscape',
    },
    {
        name:'The-Weather-App',
        image: 'src/assets/projects/theWeatherApp.png',
        description: "The Weather App is a responsive web application (Single Page Application) developed with Angular 16.1.5 that provides real-time weather information based on the user's location upon opening the page",
        technologies: [logosLanguages[2],logosLanguages[3],logosFrameworks[0], logosLanguages[1]],
        ghLink:'https://github.com/EduGese/The-Weather-App',
        demoLink: 'https://github.com/user-attachments/assets/1a07efd3-a8c5-4741-8e36-13943954d3fe',
        websiteLink: 'https://weatherapp-beff9.web.app/',
        gif:'src/assets/gifs/weatherApp.gif',
        gifOrientation:'landscape',
    },
    {
        name:'TourNow',
        image: 'src/assets/projects/tourNow.png',
        description: 'Repositorio del proyecto FCT del ciclo formativo Desarrollo de Aplicaciones Web',
        technologies: [logosLanguages[0],logosLanguages[3],logosLanguages[5],logosFrameworks[6], logosDatabase[0]],
        ghLink: 'https://github.com/EduGese/TourNow?tab=readme-ov-file',
        demoLink: 'https://youtu.be/D3eg3gU_CTs',
        websiteLink: null,
        gif:'src/assets/gifs/TourNow.gif',
        gifOrientation:'landscape',
    },
    {
        name:'Esquivaman',
        image: 'src/assets/projects/esquivaman.png',
        description: 'Videogame mobile app developed with Android Studio',
        technologies: [logosLanguages[4], logosTools[1]],
        ghLink: 'https://github.com/EduGese/EsquivamanAndroidStudiovideogame?tab=readme-ov-file',
        demoLink: 'https://github.com/user-attachments/assets/d390a75f-14a0-47aa-a658-70a5b6e2e0db',
        websiteLink: null,
        gif:'src/assets/gifs/esquivaman.gif',
        gifOrientation:'landscape',
    },
    {
        name:'EGS-Photography',
        image: 'src/assets/projects/EGS-Photography.png',
        description: 'A conceptual mockup of a photography website, designed to showcase the visual style and user interactions. While interactive elements such as a search bar and shopping cart are included, they do not have any backend functionality ',
        technologies: [logosLanguages[2],logosLanguages[3],logosFrameworks[5]],
        ghLink: 'https://github.com/EduGese/EGS-Photography',
        demoLink: 'https://edugese.github.io/EGS-Photography/',
        websiteLink: 'https://edugese.github.io/EGS-Photography/',
        gif:'src/assets/gifs/EGS-Photography.gif',
        gifOrientation:'landscape',
    }
]
